### ISSUE TITLE
I think this is definitely a good plugin

### ISSUE THREAD

**Issue by l104208470** [flammified/terrabot#1]
But how do I use it?
I have used the PIP3 installation And how do I go on

This plugin can be used together with Tshock?
Thank you

**Comment by flammified** [comment]
This is not really a plugin, it is a python library which other programs can use to make a terraria bot. You can use it by installing it using pip and then running the example while you are running a terraria server on the same computer or changing the ip to a local computer with a server. 

To answer the question about Tshock: it can be used with any terraria server, tshock or official. It simulates the protocol the official client uses, so it doesnt matter. It is however pretty incomplete, so if you would like to extend is, feel free :)
