### ISSUE TITLE
Blank character name

### ISSUE THREAD

**Issue by CrackThrough** [flammified/terrabot#6]
# Issue
I passed correct protocol number to method, and whatever I do it returns this error on server side (client doesn't log at all since server kicks the client.)

I am using **tShock** for the server.
Server's terraria version is **1.4.0.5**
tShock version is **4.4.0.0**

# Details
Server-side log looks like this:

> 192.168.0.8:63469 is connecting...
> Debug: Bouncer / OnGetSection rejected empty player name.
> 192.168.0.8:63469 was booted: Kicked: Your client sent a blank character name.
> Kicked  for : 'Your client sent a blank character name.'
> Saving world...

Here's my entire code:
```python
from terrabot.events import Events
from terrabot import TerraBot

# Create a TerraBot object
bot = TerraBot('192.168.0.8', name="thisisalongname2", protocol=230)
event = bot.get_event_manager()

# Connect a function to an event using a decorator


@event.on_event(Events.Chat)
def chat(event_id, msg):
    # Do something with the message
    # In this case, stop the bot if the word "Stop" occurs
    print(msg)
    bot.message("ddd?")
    if "!e498r7afdc6" in msg:
        bot.stop()


# Start the bot
bot.start()

# And wait
while bot.client.running:
    pass

```

**Comment by Preta-Crowz** [comment]
Caused by missing data on [packet4](https://github.com/flammified/terrabot/blob/master/terrabot/packets/packet4.py)
